/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	time "time"

	v1alpha1 "github.com/container-object-storage-interface/api/apis/objectstorage.k8s.io/v1alpha1"
	internalinterfaces "github.com/container-object-storage-interface/api/informers/internalversion/internalinterfaces"
	internalversion "github.com/container-object-storage-interface/api/listers/v1alpha1/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	internalclientset "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset"
)

// BucketAccessClassInformer provides access to a shared informer and lister for
// BucketAccessClasses.
type BucketAccessClassInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.BucketAccessClassLister
}

type bucketAccessClassInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBucketAccessClassInformer constructs a new informer for BucketAccessClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBucketAccessClassInformer(client internalclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBucketAccessClassInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBucketAccessClassInformer constructs a new informer for BucketAccessClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBucketAccessClassInformer(client internalclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Objectstorage().BucketAccessClasses().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Objectstorage().BucketAccessClasses().Watch(context.TODO(), options)
			},
		},
		&v1alpha1.BucketAccessClass{},
		resyncPeriod,
		indexers,
	)
}

func (f *bucketAccessClassInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBucketAccessClassInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bucketAccessClassInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&v1alpha1.BucketAccessClass{}, f.defaultInformer)
}

func (f *bucketAccessClassInformer) Lister() internalversion.BucketAccessClassLister {
	return internalversion.NewBucketAccessClassLister(f.Informer().GetIndexer())
}
